### ISSUE TITLE
Getting an import error and missing LDSR

### ISSUE THREAD

**Issue by LanderMcGoblin** [AUTOMATIC1111/stable-diffusion-webui-feature-showcase#12]
Hi, so i've been trying to get a fresh install but been running with the same issue. when running the webui-user.bat everything runs fine and then gives the issues below. any help would be appreciated.
already tried running from same drive where all dependencies are in and redownloading everything.

Installing requirements for CodeFormer
Installing requirements for Web UI
Launching Web UI with arguments:
Warning: LDSR not found at path D:\[003] Downloads\Dependencies\stable-diffusion-webui\repositories\latent-diffusion\LDSR.py
Traceback (most recent call last):
  File "D:\[003] Downloads\Dependencies\stable-diffusion-webui\launch.py", line 139, in <module>
    start_webui()
  File "D:\[003]  Downloads\Dependencies\stable-diffusion-webui\launch.py", line 135, in start_webui
    import webui
  File "D:\[003] Downloads\Dependencies\stable-diffusion-webui\webui.py", line 10, in <module>
    import modules.esrgan_model as esrgan
  File "D:\[003] Downloads\Dependencies\stable-diffusion-webui\modules\esrgan_model.py", line 9, in <module>
    from modules import shared, modelloader, images
  File "D:\[003] Downloads\Dependencies\stable-diffusion-webui\modules\images.py", line 11, in <module>
    from fonts.ttf import Roboto
ImportError: cannot import name 'Roboto' from 'fonts.ttf' (D:\[003] Downloads\Dependencies\stable-diffusion-webui\venv\lib\site-packages\fonts\ttf\__init__.py)
Press any key to continue...

**Comment by agarzon** [comment]
I believed the issue must be reported here https://github.com/AUTOMATIC1111/stable-diffusion-webui

This repository is only a showcase for the [stable-diffusion-webui project](https://github.com/AUTOMATIC1111/stable-diffusion-webui).
